[package]
name = "clear-cache"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "linux")'.dependencies]
libc = { version = "0.2", default-features = false }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.58", features = ["Win32_System_Threading", "Win32_System_Diagnostics_Debug"] }
